# Generated by Django 5.1.7 on 2025-03-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='class_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='roll',
            field=models.CharField(default='default_roll', max_length=20, unique=True),
        ),
    ]
