# Generated by Django 5.1.7 on 2025-03-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_userinfo_class_name_userinfo_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='roll',
            field=models.CharField(max_length=20),
        ),
    ]
