# Generated by Django 5.1.7 on 2025-03-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_userinfo_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='year',
            field=models.IntegerField(default=2023),
            preserve_default=False,
        ),
    ]
