# Generated by Django 5.1.7 on 2025-03-21 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_userinfo_address_userinfo_dob_userinfo_documents_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'RK_FUTURE_SCHOOL_INFO', 'verbose_name_plural': 'RK_FUTURE_SCHOOL_INFO'},
        ),
    ]
